"""empty message

Revision ID: 59714c03db2a
Revises: 5d052dead829
Create Date: 2024-03-18 14:31:02.489760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59714c03db2a'
down_revision = '5d052dead829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.alter_column('timeframe',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.alter_column('timeframe',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('notification')
    # ### end Alembic commands ###
