"""empty message

Revision ID: 3821f6673dbb
Revises: bf0a6fe6cce3
Create Date: 2024-03-12 14:06:28.963215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3821f6673dbb'
down_revision = 'bf0a6fe6cce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeframe', sa.String(), nullable=True))
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('timeframe')

    # ### end Alembic commands ###
