"""empty message

Revision ID: bf0a6fe6cce3
Revises: 48dbb9a7c8cf
Create Date: 2024-03-12 01:02:00.892082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0a6fe6cce3'
down_revision = '48dbb9a7c8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Responsibilities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_column('Responsibilities')

    # ### end Alembic commands ###
